# Page settings

baseurl = "https://jcr.atom.im"
languageCode = "en-us"
title = "学术期刊分区"

# Do not build files for websites. Need them? Set to false
disableKinds=["404", "RSS", "sitemap"]

[blackfriday]
  fractions = false
  hrefTargetBlank = true

[params]

	# Meta
    description = "学术期刊分区"
    keywords = "ccf, ranking list, conference, journal, computer science and technology"
    author = "Hu WAN"

    [params.info]
        enable = true
        info = "**链接**: [中国计算机学会推荐国际学术会议和期刊目录](https://ccf.atom.im)、[最新SCI影响因子查询及期刊投稿分析系统](http://www.letpub.com.cn/index.php?page=journalapp)"

    # Footer section
    [params.footer]
        copyright = "Theme designed by [dblp](https://dblp.uni-trier.de/), customized by [atom.im](https://atom.im/)."

    # Introduction section
    [params.intro]
        enable = true
        title = "学术期刊分区"

   # CCF rank list section
    [params.ccf]
        enable = true
		num = "ISSN"
		abbr = "期刊简称"
		fullname = "期刊名称"
		publisher = "中科院JCR大类分区 (2017.11)"
		rank = "中科院JCR小类分区 (2017.11)"
		type = "CCF分类排名"
		field = "InCites JCR (2016/2015)"

	[[params.ccf.list]]
		num = "0001-0782"
		abbr = "COMMUN ACM"
		fullname = "COMMUNICATIONS OF THE ACM"
		publisher = "2"
		rank = "1"
		type = "-"
		field = "Q1"

	[[params.ccf.list]]
		num = "0004-5411"
		abbr = "J ACM"
		fullname = "JOURNAL OF THE ACM"
		publisher = "3"
		rank = "2"
		type = "A"
		field = "Q2/Q1"

	[[params.ccf.list]]
		num = "0018-9219"
		abbr = "P IEEE"
		fullname = "PROCEEDINGS OF THE IEEE"
		publisher = "1"
		rank = "1"
		type = "A"
		field = "Q1"


	[[params.ccf.list]]
		num = "0018-9340"
		abbr = "IEEE T COMPUT"
		fullname = "IEEE TRANSACTIONS ON COMPUTERS"
		publisher = "3"
		rank = "2"
		type = "A"
		field = "Q1"


	[[params.ccf.list]]
		num = "0018-9529"
		abbr = "IEEE T RELIAB"
		fullname = "IEEE TRANSACTIONS ON RELIABILITY"
		publisher = "3"
		rank = "2"
		type = "-"
		field = "Q1"

	[[params.ccf.list]]
		num = "0164-0925"
		abbr = "ACM T PROGR LANG SYS"
		fullname = "ACM TRANSACTIONS ON PROGRAMMING LANGUAGES AND SYSTEMS"
		publisher = "3"
		rank = "2"
		type = "A"
		field = "Q1/Q2"

	[[params.ccf.list]]
		num = "0164-1212"
		abbr = "J SYST SOFTWARE"
		fullname = "JOURNAL OF SYSTEMS AND SOFTWARE"
		publisher = "3"
		rank = "2"
		type = "B"
		field = "Q1"

	[[params.ccf.list]]
		num = "0167-739X"
		abbr = "FUTURE GENER COMP SY"
		fullname = "Future Generation Computer Systems-The International Journal of eScience"
		publisher = "2"
		rank = "2"
		type = "-"
		field = "Q1"

	[[params.ccf.list]]
		num = "0278-0070"
		abbr = "IEEE T COMPUT AID D"
		fullname = "IEEE TRANSACTIONS ON COMPUTER-AIDED DESIGN OF INTEGRATED CIRCUITS AND SYSTEMS"
		publisher = "4"
		rank = "3"
		type = "A"
		field = "Q2"

	[[params.ccf.list]]
		num = "0308-1079"
		abbr = "INT J GEN SYST"
		fullname = "INTERNATIONAL JOURNAL OF GENERAL SYSTEMS"
		publisher = "3"
		rank = "2"
		type = "-"
		field = "Q1"

	[[params.ccf.list]]
		num = "0360-0300"
		abbr = "ACM COMPUT SURV"
		fullname = "ACM COMPUTING SURVEYS"
		publisher = "1"
		rank = "1"
		type = "-"
		field = "Q1"

	[[params.ccf.list]]
		num = "0362-5915"
		abbr = "ACM T DATABASE SYST"
		fullname = "ACM TRANSACTIONS ON DATABASE SYSTEMS"
		publisher = "4"
		rank = "4"
		type = "A"
		field = "Q3/Q4"

	[[params.ccf.list]]
		num = "0734-2071"
		abbr = "ACM T COMPUT SYST"
		fullname = "ACM TRANSACTIONS ON COMPUTER SYSTEMS"
		publisher = "2"
		rank = "2"
		type = "A"
		field = "Q1"

	[[params.ccf.list]]
		num = "1041-4347"
		abbr = "IEEE T KNOWL DATA EN"
		fullname = "IEEE TRANSACTIONS ON KNOWLEDGE AND DATA ENGINEERING"
		publisher = "2"
		rank = "2"
		type = "A"
		field = "Q1"

	[[params.ccf.list]]
		num = "1045-9219"
		abbr = "IEEE T PARALL DISTR"
		fullname = "IEEE TRANSACTIONS ON PARALLEL AND DISTRIBUTED SYSTEMS"
		publisher = "2"
		rank = "2"
		type = "A"
		field = "Q1"

	[[params.ccf.list]]
		num = "1066-8888"
		abbr = "VLDB J"
		fullname = "VLDB JOURNAL"
		publisher = "2"
		rank = "2"
		type = "A"
		field = "Q1"

	[[params.ccf.list]]
		num = "1084-8045"
		abbr = "J NETW COMPUT APPL"
		fullname = "JOURNAL OF NETWORK AND COMPUTER APPLICATIONS"
		publisher = "2"
		rank = "1"
		type = "-"
		field = "Q1"

	[[params.ccf.list]]
		num = "1536-1233"
		abbr = "IEEE T MOBILE COMPUT"
		fullname = "IEEE TRANSACTIONS ON MOBILE COMPUTING"
		publisher = "2"
		rank = "2"
		type = "A"
		field = "Q1"

	[[params.ccf.list]]
		num = "1553-3077"
		abbr = "ACM T STORAGE"
		fullname = "ACM Transactions on Storage"
		publisher = "4"
		rank = "4"
		type = "A"
		field = "Q2/Q3"

	[[params.ccf.list]]
		num = "2168-6750"
		abbr = "IEEE T EMERG TOP COM"
		fullname = "IEEE Transactions on Emerging Topics in Computing"
		publisher = "2"
		rank = "2"
		type = "-"
		field = "Q1"
